# Generated by Django 3.0.1 on 2020-01-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanics',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Mechanics',
        ),
    ]
